# Generated by Django 3.0 on 2019-12-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristique',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
